# -*- coding: utf-8 -*-
"""
Matha REPL 独立可执行文件 - PyInstaller 配置文件

构建命令:
    pyinstaller --onefile matha.spec
"""

a = Analysis(
    ['src/repl.py'],
    pathex=[],
    binaries=[],
    datas=[
        # 包含标准库和测试数据（可选）
    ],
    hiddenimports=[
        # 核心模块
        'src.math_driver',
        'src.compiler.matha_cc',
        'src.mir',
        'src.mir_codegen',
        'src.mir_converter',
        'src.compiler.memoize',
        'src.compiler.jit',
        'src.compiler.llvm_hybrid',
        'src.compiler.aot',
        'src.profiler',
        'src.lsp',
        'src.doc_gen',
        'src.pkg_manager_v2',
        'src.tree_sitter_backends',
        'src.multi_lang_codegen',
        'src.multi_lang_verifier',
        'src.csp_os_thread',
        'src.performance_benchmark',
        'src.type_system_v2',
        'src.offline_store',
        'src.offline.sqlite_storage',
        'src.offline.sync',
        'src.offline.mobile_api_client',
        'src.stdlib.core',
        'src.stdlib.arithmetic',
        'src.stdlib.calculus',
        'src.stdlib.calculus_symbolic',
        'src.stdlib.linear_algebra',
        'src.stdlib.probability_stats',
        'src.stdlib.logic',
        'src.intent_parser',
        'src.repl_completion',
        'src.repl_highlight',
        'src.repl_v23',
        'src.result',
        'src.interp',
        'src.parser',
        'src.ast_nodes',
        'src.tokens',
        'src.lexer',
        'src.semantic',
        'src.symbolic',
        'src.symbols',
        'src.diagnostics',
        # 领域模块（核心物理/工程）
        'src.domains.hal',
        'src.domains.kernel_math',
        'src.domains.software_app',
        'src.domains.hardware',
        'src.domains.acoustics',
        'src.domains.aerospace',
        'src.domains.ai_data_science',
        'src.domains.algo_trading',
        'src.domains.anatomy',
        'src.domains.architecture',
        'src.domains.audio_video',
        'src.domains.automation',
        'src.domains.autonomous',
        'src.domains.biology',
        'src.domains.bio_computing',
        'src.domains.blockchain',
        'src.domains.building_struct',
        'src.domains.celestial',
        'src.domains.chaos_fractal',
        'src.domains.chemistry',
        'src.domains.computer_science',
        'src.domains.comp_chem',
        'src.domains.creative_coding',
        'src.domains.digital_rights',
        'src.domains.dynamics',
        'src.domains.economics',
        'src.domains.electrical',
        'src.domains.em',
        'src.domains.embedded',
        'src.domains.extended_modeling',
        'src.domains.fintech',
        'src.domains.fluid',
        'src.domains.fluid_exp',
        'src.domains.game_dev',
        'src.domains.genetic_algo',
        'src.domains.graph',
        'src.domains.graphics',
        'src.domains.green_tech',
        'src.domains.hpc',
        'src.domains.iot_hardware',
        'src.domains.kernel',
        'src.domains.mechanics',
        'src.domains.mech_design',
        'src.domains.medical',
        'src.domains.medtools',
        'src.domains.metaverse_arch',
        'src.domains.nuclear',
        'src.domains.optics',
        'src.domains.os_network',
        'src.domains.quantum',
        'src.domains.quantum_compute',
        'src.domains.real_hardware',
        'src.domains.registry',
        'src.domains.spatial_meta',
        'src.domains.statmech',
        'src.domains.structural',
        'src.domains.thermo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter',
        'pytest',
        'unittest',
        'IPython',
        'jupyter',
        'notebook',
        'flask',
        'django',
        'openai',
        'anthropic',
        'google.generativeai',
        'requests',
        'numpy',
        'scipy',
        'numba',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='matha',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # 保留控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

# 打包为单文件
a_onedir = Analysis(
    ['src/repl.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=a.hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=a.excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz_onedir = PYZ(a_onedir.pure)

exe_onedir = EXE(
    pyz_onedir,
    a_onedir.scripts,
    a_onedir.binaries,
    a_onedir.datas,
    [],
    name='matha',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
