/* Generated by matha2c from .\runtime\test_ascii.matha */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>

#define MATHA_PI   3.14159265358979323846
#define MATHA_E    2.71828182845904523536
#define MATHA_TAU  (2.0 * MATHA_PI)
#define MATHA_PHI  ((1.0 + sqrt(5.0)) / 2.0)
#define MATHA_LN2  0.6931471805599453

#define MATHA_MAX_NODES 65536
#define MATHA_MAX_FUNCS  512


/* Module: Test */

static const double x = 42;

int main(int argc, char* argv[]) {
  return 0;
}
