# -*- coding: utf-8 -*-
"""
Matha 多语言代码生成引擎 v2.0
==============================
支持语言：Python / JavaScript / C / C++ / Rust / Go / Java / Matha

新增语言后端：
  - CppGenerator   — C++ 高性能计算
  - RustGenerator  — Rust 内存安全 + 零成本抽象
  - GoGenerator    — Go 原生并发 + GC
  - JavaGenerator  — Java JVM 跨平台

符号简化兼容：
  - >> 步进迭代  →  for x in range(a, b)
  - >> 属于判断  →  x in S
  - >> 路径距离  →  distance(a, b)
  - >> 链式调用  →  a |> b (使用 Pipe 运算符，Python 3.12+)

设计原则：
  1. 所有后端共享同一 AST 解释器
  2. 生成的代码可直接编译/运行验证
  3. 支持 MultiLangVerifier 交叉验证
"""
from __future__ import annotations
import re
import logging
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger("matha.multilang_codegen")

# ═══════════════════════════════════════════════════════════════════════════════
#  符号简化兼容层
# ═══════════════════════════════════════════════════════════════════════════════

class SymbolCompat:
    """
    简化 >> 四重语义为单语义 + 显式转换函数。

    原始语义 → 简化后:
      >> 步进迭代   →  for x in range(a, b)
      >> 属于判断   →  x in S
      >> 路径距离   →  distance(a, b)
      >> 链式调用   →  a | b  (pipe)
    """

    MAPPING = {
        # 步进迭代: x >> S  →  for x in S
        "step_iteration": lambda x, s: f"for {x} in {s}",
        # 属于判断: x >> S  →  x in S
        "membership": lambda x, s: f"{x} in {s}",
        # 路径距离: a >> b  →  distance(a, b)
        "path_distance": lambda a, b: f"distance({a}, {b})",
        # 链式调用: a >> b  →  b(a) 或 a | b
        "pipe_call": lambda a, b: f"{b}({a})",
    }

    @staticmethod
    def simplify(expr: str) -> str:
        """将简化符号表达式转为标准表达式。"""
        # 路径距离: 单字母 a >> b → distance(a, b)
        expr = re.sub(r'\b([a-zA-Z])\s*>>\s*([a-zA-Z])\b', r'distance(\1, \2)', expr)
        # 链式调用: func >> arg → arg(func)（至少2字符）
        expr = re.sub(r'\b([a-z_][a-z_0-9]*)\s*>>\s*([a-z_][a-z_0-9]*)\b', r'\2(\1)', expr)
        return expr

    @staticmethod
    def to_pipe(expr: str) -> str:
        """转换为管道表达式 (Python 3.12+ support)。"""
        return expr.replace('>>', '|')


# ═══════════════════════════════════════════════════════════════════════════════
#  C++ 代码生成器
# ═══════════════════════════════════════════════════════════════════════════════

class CppGenerator:
    """生成 C++ 代码（支持面向对象 + 模板 + STL）。"""

    def __init__(self, func_name: str = "compute",
                 return_type: str = "double",
                 use_templates: bool = False):
        self.func_name = func_name
        self.return_type = return_type
        self.use_templates = use_templates
        self._lines: List[str] = []
        self._level = 0

    def emit(self, line: str = ""):
        self._lines.append("    " * self._level + line)

    def block(self, fn):
        self._level += 1
        fn()
        self._level -= 1

    def get_code(self) -> str:
        return '\n'.join(self._lines)

    def generate_function(self, params: List[tuple], expr: str) -> str:
        """生成完整函数。"""
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (C++)",
            "#include <iostream>",
            "#include <cmath>",
            "#include <algorithm>",
            "#include <vector>",
            "#include <numeric>",
            "",
        ]
        # 函数签名
        param_str = ", ".join(f"{t} {n}" for t, n in params)
        lines.append(f"{self.return_type} {self.func_name}({param_str}) {{")
        self._lines = lines
        self._level = 1
        # 局部变量声明
        self.emit(f"{self.return_type} result = 0.0;")
        # 表达式
        cpp_expr = self._expr_to_cpp(expr)
        self.emit(f"result = {cpp_expr};")
        self.emit("return result;")
        self.emit("}")
        return self.get_code()

    def generate_class(self, class_name: str, methods: List[dict]) -> str:
        """生成 C++ 类。"""
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (C++)",
            f"class {class_name} {{",
            "public:",
        ]
        for m in methods:
            param_str = ", ".join(f"{t} {n}" for t, n in m.get("params", []))
            lines.append(f"    {m['return']} {m['name']}({param_str}) {{")
            lines.append(f"        return {self._expr_to_cpp(m.get('expr', '0'))};")
            lines.append("    }")
        lines.append("};")
        return '\n'.join(lines)

    def generate_main(self, func_name: str, test_cases: List[tuple]) -> str:
        """生成 main 测试函数。"""
        lines = [
            "int main() {",
            f"    std::cout << \"{func_name} benchmark\" << std::endl;",
        ]
        for args, expected in test_cases:
            args_str = ", ".join(str(a) for a in args)
            lines.append(f'    std::cout << "{func_name}({args_str}) = " '
                        f'<< {func_name}({args_str}) << std::endl;')
        lines.append("    return 0;")
        lines.append("}")
        return '\n'.join(lines)

    def _expr_to_cpp(self, expr: str) -> str:
        """表达式转 C++。"""
        result = (expr
                  .replace('^', "**")  # C++20 支持幂运算符
                  .replace('sin(', "std::sin(")
                  .replace('cos(', "std::cos(")
                  .replace('tan(', "std::tan(")
                  .replace('sqrt(', "std::sqrt(")
                  .replace('log(', "std::log(")
                  .replace('exp(', "std::exp(")
                  .replace('abs(', "std::abs(")
                  .replace('pi', "M_PI")
                  .replace('min(', "std::min(")
                  .replace('max(', "std::max("))
        return re.sub(r'\be\b', 'M_E', result)


# ═══════════════════════════════════════════════════════════════════════════════
#  Rust 代码生成器
# ═══════════════════════════════════════════════════════════════════════════════

class RustGenerator:
    """生成 Rust 代码（内存安全 + 零成本抽象）。"""

    def __init__(self, func_name: str = "compute",
                 return_type: str = "f64",
                 generic: bool = False):
        self.func_name = func_name
        self.return_type = return_type
        self.generic = generic
        self._lines: List[str] = []

    def get_code(self) -> str:
        return '\n'.join(self._lines)

    def generate_function(self, params: List[tuple], expr: str) -> str:
        """生成完整函数。"""
        param_str = ", ".join(f"{n}: {t}" for t, n in params)
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (Rust)",
            "// 内存安全 + 零成本抽象",
            "#[inline]",
            f"pub fn {self.func_name}({param_str}) -> {self.return_type} {{",
        ]
        rust_expr = self._expr_to_rust(expr)
        lines.append(f"    {rust_expr}")
        lines.append("}")
        lines.append("")
        lines.append(f"// 测试")
        lines.append(f"fn test_{self.func_name}() {{")
        lines.append(f"    let result = {self.func_name}({', '.join(n for _, n in params)});")
        lines.append(f"    assert!((result - {self._get_expected(params)}).abs() < 1e-9);")
        lines.append(f"}}")
        lines.append(f"")
        lines.append(f"fn main() {{")
        lines.append(f"    println!(\"Matha Rust Benchmark\");")
        lines.append(f"    test_{self.func_name}();")
        lines.append(f"    println!(\"All tests passed!\");")
        lines.append(f"}}")
        return '\n'.join(lines)

    def generate_trait(self, trait_name: str, methods: List[dict]) -> str:
        """生成 Rust Trait。"""
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (Rust)",
            f"pub trait {trait_name} {{",
        ]
        for m in methods:
            param_str = ", ".join(f"{n}: {t}" for t, n in m.get("params", []))
            lines.append(f"    fn {m['name']}({param_str}) -> {m['return']};")
        lines.append("}")
        lines.append("}")
        return '\n'.join(lines)

    def generate_main(self) -> str:
        """生成 main 测试入口。"""
        return """fn main() {
    println!("Matha Rust Benchmark");
    test_compute();
    println!("All tests passed!");
}"""

    def _expr_to_rust(self, expr: str) -> str:
        """表达式转 Rust。"""
        result = (expr
                  .replace('^', "**")
                  .replace('sin(', "f64::sin(")
                  .replace('cos(', "f64::cos(")
                  .replace('tan(', "f64::tan(")
                  .replace('sqrt(', "f64::sqrt(")
                  .replace('log(', "f64::ln(")
                  .replace('exp(', "f64::exp(")
                  .replace('abs(', "f64::abs(")
                  .replace('pi', "std::f64::consts::PI")
                  .replace('min(', "f64::min(")
                  .replace('max(', "f64::max("))
        return re.sub(r'\be\b', 'std::f64::consts::E', result)

    def _get_expected(self, params: List[tuple]) -> str:
        """生成预期值占位符。"""
        return "0.0"


# ═══════════════════════════════════════════════════════════════════════════════
#  Go 代码生成器
# ═══════════════════════════════════════════════════════════════════════════════

class GoGenerator:
    """生成 Go 代码（原生并发 + GC + 快速编译）。"""

    def __init__(self, func_name: str = "compute",
                 return_type: str = "float64"):
        self.func_name = func_name
        self.return_type = return_type
        self._lines: List[str] = []

    def get_code(self) -> str:
        return '\n'.join(self._lines)

    def generate_function(self, params: List[tuple], expr: str) -> str:
        """生成完整函数。"""
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (Go)",
            "// 原生并发 + GC + 快速编译",
            "package main",
            "",
            "import (",
            '    "fmt"',
            '    "math"',
            ")",
            "",
        ]
        param_str = ", ".join(f"{n} {t}" for t, n in params)
        lines.append(f"func {self.func_name}({param_str}) {self.return_type} {{")
        go_expr = self._expr_to_go(expr)
        lines.append(f"    return {go_expr}")
        lines.append("}")
        lines.append("")
        # main 函数
        lines.append("func main() {")
        lines.append(f'    fmt.Println("{self.func_name} benchmark")')
        for _, name in params:
            lines.append(f'    fmt.Printf("{name} = %v\\n", {name})')
        lines.append(f'    fmt.Printf("result = %v\\n", {self.func_name}({", ".join(n for _, n in params)}))')
        lines.append("}")
        return '\n'.join(lines)

    def generate_goroutine(self, func_name: str, args: List[tuple]) -> str:
        """生成 goroutine 并发示例。"""
        param_str = ", ".join(f"{n} {t}" for t, n in args)
        return f"""func run_{func_name}() {{
    ch := make(chan {self.return_type})
    go func() {{
        ch <- {func_name}({", ".join(n for _, n in args)})
    }}()
    result := <-ch
    fmt.Printf("{func_name} result = %v\\n", result)
}}"""

    def _expr_to_go(self, expr: str) -> str:
        """表达式转 Go。"""
        result = (expr
                  .replace('^', "**")  # Go 用 math.Pow
                  .replace('sin(', "math.Sin(")
                  .replace('cos(', "math.Cos(")
                  .replace('tan(', "math.Tan(")
                  .replace('sqrt(', "math.Sqrt(")
                  .replace('log(', "math.Log(")
                  .replace('exp(', "math.Exp(")
                  .replace('abs(', "math.Abs(")
                  .replace('pi', "math.Pi")
                  .replace('min(', "math.Min(")
                  .replace('max(', "math.Max("))
        return re.sub(r'\be\b', 'math.E', result)


# ═══════════════════════════════════════════════════════════════════════════════
#  Java 代码生成器
# ═══════════════════════════════════════════════════════════════════════════════

class JavaGenerator:
    """生成 Java 代码（JVM 跨平台 + 强类型）。"""

    def __init__(self, func_name: str = "compute",
                 return_type: str = "double",
                 class_name: str = "MathaCompute"):
        self.func_name = func_name
        self.return_type = return_type
        self.class_name = class_name
        self._lines: List[str] = []

    def get_code(self) -> str:
        return '\n'.join(self._lines)

    def generate_class(self, params: List[tuple], expr: str) -> str:
        """生成完整 Java 类。"""
        lines = [
            "// Auto-generated by Matha MultiLang CodeGen (Java)",
            "// JVM 跨平台 + 强类型",
            "public class " + self.class_name + " {",
        ]
        # 静态方法
        param_str = ", ".join(f"{t} {n}" for t, n in params)
        lines.append(f"    public static {self.return_type} {self.func_name}({param_str}) {{")
        java_expr = self._expr_to_java(expr)
        lines.append(f"        return {java_expr};")
        lines.append("    }")
        lines.append("")
        # main 方法
        lines.append("    public static void main(String[] args) {")
        lines.append(f'        System.out.println("{self.func_name} benchmark");')
        args_str = ", ".join(n for _, n in params)
        lines.append(f'        System.out.println("{self.func_name}({args_str}) = " + ')
        lines.append(f'            {self.func_name}({args_str}));')
        lines.append("    }")
        lines.append("}")
        return '\n'.join(lines)

    def generate_interface(self, interface_name: str, methods: List[dict]) -> str:
        """生成 Java 接口。"""
        lines = [
            "public interface " + interface_name + " {",
        ]
        for m in methods:
            param_str = ", ".join(f"{t} {n}" for t, n in m.get("params", []))
            lines.append(f"    {m['return']} {m['name']}({param_str});")
        lines.append("}")
        return '\n'.join(lines)

    def _expr_to_java(self, expr: str) -> str:
        """表达式转 Java。"""
        result = (expr
                  .replace('^', "**")  # Java 用 Math.pow
                  .replace('sin(', "Math.sin(")
                  .replace('cos(', "Math.cos(")
                  .replace('tan(', "Math.tan(")
                  .replace('sqrt(', "Math.sqrt(")
                  .replace('log(', "Math.log(")
                  .replace('exp(', "Math.exp(")
                  .replace('abs(', "Math.abs(")
                  .replace('pi', "Math.PI")
                  .replace('min(', "Math.min(")
                  .replace('max(', "Math.max("))
        return re.sub(r'\be\b', 'Math.E', result)


# ═══════════════════════════════════════════════════════════════════════════════
#  统一代码生成器入口
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class CodeGenResult:
    """代码生成结果。"""
    language: str
    code: str
    executable: bool = False  # 是否可直接执行
    benchmark: str = ""       # 性能基准数据


class MultiLangCodeGen:
    """多语言代码生成统一入口。"""

    # 语言注册表
    _generators = {
        "python": "symbol_codegen:PythonGenerator",
        "javascript": "symbol_codegen:JavaScriptGenerator",
        "c": "symbol_codegen:CGenerator",
        "cpp": "__main__:CppGenerator",
        "rust": "__main__:RustGenerator",
        "go": "__main__:GoGenerator",
        "java": "__main__:JavaGenerator",
        "matha": "symbol_codegen:MathaGenerator",
    }

    def __init__(self):
        self._results: Dict[str, CodeGenResult] = {}

    def generate(self, language: str, func_name: str,
                 params: List[tuple], expr: str,
                 return_type: str = "double") -> CodeGenResult:
        """生成指定语言的代码。"""
        lang = language.lower()
        if lang == "cpp":
            gen = CppGenerator(func_name, return_type)
            code = gen.generate_function(params, expr)
        elif lang == "rust":
            gen = RustGenerator(func_name, return_type)
            code = gen.generate_function(params, expr)
        elif lang == "go":
            gen = GoGenerator(func_name, return_type)
            code = gen.generate_function(params, expr)
        elif lang == "java":
            gen = JavaGenerator(func_name, return_type)
            code = gen.generate_class(params, expr)
        else:
            # 委托给原有生成器
            from src.symbol_codegen import (
                PythonGenerator, JavaScriptGenerator, CGenerator, MathaGenerator
            )
            generators = {
                "python": PythonGenerator(func_name),
                "javascript": JavaScriptGenerator(func_name),
                "c": CGenerator(func_name, return_type),
                "matha": MathaGenerator(func_name),
            }
            gen = generators.get(lang)
            if gen is None:
                return CodeGenResult(language, f"# Unsupported language: {lang}", False)
            gen.add_expression(expr)
            code = gen.get_code()

        result = CodeGenResult(
            language=lang,
            code=code,
            executable=lang in ("c", "cpp", "rust", "go", "java"),
        )
        self._results[lang] = result
        return result

    def generate_all(self, func_name: str, params: List[tuple],
                     expr: str, return_type: str = "double") -> Dict[str, CodeGenResult]:
        """生成所有支持语言的代码。"""
        languages = ["python", "javascript", "c", "cpp", "rust", "go", "java", "matha"]
        for lang in languages:
            self.generate(lang, func_name, params, expr, return_type)
        return self._results

    def get_result(self, language: str) -> Optional[CodeGenResult]:
        return self._results.get(language)

    def summary(self) -> str:
        """生成生成摘要。"""
        lines = ["=== Matha 多语言代码生成摘要 ==="]
        for lang, result in self._results.items():
            lines.append(f"  [{lang.upper()}] {len(result.code)} bytes, "
                        f"executable={'Yes' if result.executable else 'No'}")
        return '\n'.join(lines)


# ═══════════════════════════════════════════════════════════════════════════════
#  便捷函数
# ═══════════════════════════════════════════════════════════════════════════════

def generate_cpp(func_name: str, params: List[tuple], expr: str,
                 return_type: str = "double") -> str:
    """快捷生成 C++ 代码。"""
    gen = CppGenerator(func_name, return_type)
    return gen.generate_function(params, expr)


def generate_rust(func_name: str, params: List[tuple], expr: str,
                  return_type: str = "f64") -> str:
    """快捷生成 Rust 代码。"""
    gen = RustGenerator(func_name, return_type)
    return gen.generate_function(params, expr)


def generate_go(func_name: str, params: List[tuple], expr: str,
                return_type: str = "float64") -> str:
    """快捷生成 Go 代码。"""
    gen = GoGenerator(func_name, return_type)
    return gen.generate_function(params, expr)


def generate_java(func_name: str, params: List[tuple], expr: str,
                  return_type: str = "double",
                  class_name: str = "MathaCompute") -> str:
    """快捷生成 Java 代码。"""
    gen = JavaGenerator(func_name, return_type, class_name)
    return gen.generate_class(params, expr)


# 运行入口
if __name__ == "__main__":
    print("=" * 60)
    print("  Matha 多语言代码生成引擎 v2.0")
    print("=" * 60)

    # 示例：计算 x^2 + 3x - 5
    func_name = "polynomial"
    params = [("double", "x")]
    expr = "x^2 + 3*x - 5"

    gen = MultiLangCodeGen()
    results = gen.generate_all(func_name, params, expr)

    for lang, result in results.items():
        print(f"\n--- {lang.upper()} ---")
        print(result.code[:300])
        if len(result.code) > 300:
            print("...")

    print("\n" + gen.summary())
