# -*- coding: utf-8 -*-
"""
Matha 代码生成引擎 v1.3.0
===========================
将 Matha 符号表达式和 AST 转换为多种目标语言的执行代码。

目标语言：
  • Python  — 直接执行
  • JavaScript — 浏览器/Node.js
  • C/C++  — 高性能计算
  • Matha   — 自举回 Matha 语法

功能：
  • codegen_python   — 生成 Python 代码
  • codegen_javascript — 生成 JS 代码
  • codegen_c        — 生成 C 代码
  • codegen_matha    — 生成 Matha 代码
  • generate_driver  — 生成硬件驱动代码
  • generate_library — 生成可导入的库文件
"""
from __future__ import annotations
import sys
import os
import logging
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger("matha.codegen")

# ═══════════════════════════════════════════════════════════════════════════════
#  代码生成器基类
# ═══════════════════════════════════════════════════════════════════════════════

class CodeGenerator:
    """代码生成基类。"""

    def __init__(self, lang: str, indent: str = "  "):
        self.lang = lang
        self.indent = indent
        self._lines: List[str] = []
        self._level = 0

    def emit(self, line: str = ""):
        """输出一行代码。"""
        self._lines.append(self.indent * self._level + line)

    def block(self, body_fn):
        """代码块缩进。"""
        self._level += 1
        body_fn()
        self._level -= 1

    def get_code(self) -> str:
        """获取生成的代码。"""
        return '\n'.join(self._lines)


# ═══════════════════════════════════════════════════════════════════════════════
#  Python 代码生成
# ═══════════════════════════════════════════════════════════════════════════════

class PythonGenerator(CodeGenerator):
    """生成 Python 代码。"""

    def __init__(self, func_name: str = "compute", imports: List[str] = None):
        super().__init__("python")
        self.func_name = func_name
        self.imports = imports or []
        self._emit_header()

    def _emit_header(self):
        self.emit("# Auto-generated by Matha CodeGen")
        self.emit(f"def {self.func_name}(")
        self.emit("):")
        self.block(self._emit_body)

    def _emit_body(self):
        for imp in self.imports:
            self.emit(imp)
        self.emit("    result = ...")
        self.emit("    return result")

    def add_expression(self, expr_str: str, var_name: str = "result"):
        """添加表达式求值。"""
        py_expr = self._expr_to_python(expr_str)
        self.emit(f"    {var_name} = {py_expr}")

    def _expr_to_python(self, expr: str) -> str:
        """表达式转 Python。"""
        return (expr
                .replace('^', '**')
                .replace('sin(', 'math.sin(')
                .replace('cos(', 'math.cos(')
                .replace('tan(', 'math.tan(')
                .replace('sqrt(', 'math.sqrt(')
                .replace('log(', 'math.log(')
                .replace('exp(', 'math.exp(')
                .replace('pi', 'math.pi')
                .replace('e', 'math.e'))


# ═══════════════════════════════════════════════════════════════════════════════
#  JavaScript 代码生成
# ═══════════════════════════════════════════════════════════════════════════════

class JavaScriptGenerator(CodeGenerator):
    """生成 JavaScript 代码。"""

    def __init__(self, func_name: str = "compute", as_module: bool = False):
        super().__init__("javascript")
        self.func_name = func_name
        self.as_module = as_module
        self._emit_header()

    def _emit_header(self):
        if self.as_module:
            self.emit("// Auto-generated by Matha CodeGen")
            self.emit(f"export function {self.func_name}(")
        else:
            self.emit("// Auto-generated by Matha CodeGen")
            self.emit(f"function {self.func_name}(")
        self.emit(") {")
        self.block(self._emit_body)
        self.emit("}")

    def _emit_body(self):
        self.emit("let result = 0;")
        # Math 对象映射
        self.emit("const M = Math;")

    def add_expression(self, expr_str: str, var_name: str = "result"):
        js_expr = self._expr_to_javascript(expr_str)
        self.emit(f"let {var_name} = {js_expr};")

    def _expr_to_javascript(self, expr: str) -> str:
        return (expr
                .replace('^', '**')
                .replace('sin(', 'Math.sin(')
                .replace('cos(', 'Math.cos(')
                .replace('tan(', 'Math.tan(')
                .replace('sqrt(', 'Math.sqrt(')
                .replace('log(', 'Math.log(')
                .replace('exp(', 'Math.exp(')
                .replace('pi', 'Math.PI')
                .replace('e', 'Math.E'))


# ═══════════════════════════════════════════════════════════════════════════════
#  C 代码生成
# ═══════════════════════════════════════════════════════════════════════════════

class CGenerator(CodeGenerator):
    """生成 C 代码。"""

    def __init__(self, func_name: str = "compute", return_type: str = "double"):
        super().__init__("c")
        self.func_name = func_name
        self.return_type = return_type
        self._emit_header()

    def _emit_header(self):
        self.emit("/* Auto-generated by Matha CodeGen */")
        self.emit("#include <stdio.h>")
        self.emit("#include <math.h>")
        self.emit("")
        self.emit(f"{self.return_type} {self.func_name}(")
        self.emit(") {")
        self.block(self._emit_body)
        self.emit("}")

    def _emit_body(self):
        self.emit(f"{self.return_type} result = 0.0;")
        self.emit("return result;")

    def add_expression(self, expr_str: str, var_name: str = "result"):
        c_expr = self._expr_to_c(expr_str)
        self.emit(f"{var_name} = {c_expr};")

    def _expr_to_c(self, expr: str) -> str:
        return (expr
                .replace('^', "**")
                .replace('sin(', 'sin(')
                .replace('cos(', 'cos(')
                .replace('tan(', 'tan(')
                .replace('sqrt(', 'sqrt(')
                .replace('log(', 'log(')
                .replace('exp(', 'exp(')
                .replace('pi', 'M_PI')
                .replace('e', 'M_E'))


# ═══════════════════════════════════════════════════════════════════════════════
#  Matha 代码生成
# ═══════════════════════════════════════════════════════════════════════════════

class MathaGenerator(CodeGenerator):
    """生成 Matha 代码。"""

    def __init__(self, func_name: str = "compute"):
        super().__init__("matha")
        self.func_name = func_name
        self._emit_header()

    def _emit_header(self):
        self.emit("# Auto-generated by Matha CodeGen")
        self.emit(f"func {self.func_name}(")
        self.block(self._emit_body)
        self.emit(")")

    def _emit_body(self):
        self.emit("    result = ...")
        self.emit("    return result")

    def add_expression(self, expr_str: str, var_name: str = "result"):
        self.emit(f"    {var_name} = {expr_str}")


# ═══════════════════════════════════════════════════════════════════════════════
#  硬件驱动生成
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class DriverSpec:
    """硬件驱动规格。"""
    name: str
    language: str           # python / c / javascript
    math_func: str          # 数学函数描述
    io_type: str            # input / output / both
    precision: str = "float"
    params: Dict[str, Any] = field(default_factory=dict)


class DriverGenerator:
    """硬件驱动代码生成器。"""

    TARGETS = {
        "python": PythonGenerator,
        "c": CGenerator,
        "javascript": JavaScriptGenerator,
    }

    def __init__(self):
        logger.info("  [CodeGen] 驱动生成器初始化")

    def generate(self, spec: DriverSpec) -> str:
        """根据规格生成驱动代码。"""
        gen_cls = self.TARGETS.get(spec.language, PythonGenerator)
        gen = gen_cls(func_name=spec.name)
        gen.add_expression(spec.math_func)
        code = gen.get_code()
        logger.info(f"  [CodeGen] 生成驱动: {spec.name} ({spec.language})")
        return code

    def generate_library(self, functions: List[Dict[str, str]], lang: str = "python") -> str:
        """生成可导入库文件。"""
        gen_cls = self.TARGETS.get(lang, PythonGenerator)
        if lang == "python":
            lines = ["# Auto-generated library by Matha CodeGen", ""]
            for func in functions:
                lines.append(f"def {func['name']}(")
                lines.append(f"    # {func.get('doc', '')}")
                lines.append(f"    return {func.get('expr', '0')}")
                lines.append("")
            return '\n'.join(lines)
        return ""


# ═══════════════════════════════════════════════════════════════════════════════
#  统一代码生成器
# ═══════════════════════════════════════════════════════════════════════════════

class MathaCodeGen:
    """
    统一代码生成器 — 支持多语言目标代码生成。

    用法：
        cg = MathaCodeGen()
        cg.python("x^2 + 3*x", func_name="f")
        cg.javascript("sin(x) + cos(x)")
        cg.c("sqrt(x)", return_type="double")
        cg.matha("x + y")
    """

    def __init__(self):
        self.drivers = DriverGenerator()

    def python(self, expr: str, func_name: str = "compute",
               imports: List[str] = None) -> str:
        """生成 Python 代码。"""
        gen = PythonGenerator(func_name, imports)
        gen.add_expression(expr)
        return gen.get_code()

    def javascript(self, expr: str, func_name: str = "compute",
                   as_module: bool = False) -> str:
        """生成 JavaScript 代码。"""
        gen = JavaScriptGenerator(func_name, as_module)
        gen.add_expression(expr)
        return gen.get_code()

    def c(self, expr: str, func_name: str = "compute",
          return_type: str = "double") -> str:
        """生成 C 代码。"""
        gen = CGenerator(func_name, return_type)
        gen.add_expression(expr)
        return gen.get_code()

    def matha(self, expr: str, func_name: str = "compute") -> str:
        """生成 Matha 代码。"""
        gen = MathaGenerator(func_name)
        gen.add_expression(expr)
        return gen.get_code()

    def generate_driver(self, spec: DriverSpec) -> str:
        """生成硬件驱动代码。"""
        return self.drivers.generate(spec)

    def generate_library(self, functions: List[Dict[str, str]], lang: str = "python") -> str:
        """生成可导入库。"""
        return self.drivers.generate_library(functions, lang)


# ═══════════════════════════════════════════════════════════════════════════════
#  单例
# ═══════════════════════════════════════════════════════════════════════════════

_codegen_instance: Optional[MathaCodeGen] = None


def get_codegen() -> MathaCodeGen:
    global _codegen_instance
    if _codegen_instance is None:
        _codegen_instance = MathaCodeGen()
    return _codegen_instance


def codegen_python(expr: str, **kwargs) -> str:
    return get_codegen().python(expr, **kwargs)


def codegen_javascript(expr: str, **kwargs) -> str:
    return get_codegen().javascript(expr, **kwargs)


def codegen_c(expr: str, **kwargs) -> str:
    return get_codegen().c(expr, **kwargs)


if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("  Matha 代码生成引擎 v1.3.0")
    print("=" * 60)

    cg = MathaCodeGen()

    expr = "x^2 + 3*x - 5"

    print(f"\n原始表达式: {expr}")

    print("\n[Python]")
    print(cg.python(expr, func_name="f"))

    print("\n[JavaScript]")
    print(cg.javascript(expr, func_name="f"))

    print("\n[C]")
    print(cg.c(expr, func_name="f"))

    print("\n[Matha]")
    print(cg.matha(expr, func_name="f"))

    print("\n完成。")
