# -*- coding: utf-8 -*-
"""
TypeScript 转译器 — 将 Matha AST 转译为 TypeScript 源码

TypeScript 是 Python 的超集，额外支持类型注解和接口定义。

支持：
  - 函数定义（带类型注解）
  - 变量声明（let/const + 类型推断）
  - 表达式转译（数学函数、运算符、条件表达式）
  - 控制流（if/else、while）
  - 类型映射（float → number, bool → boolean, string → string）
"""
from __future__ import annotations
from typing import Any

from src.parser import Parser
from src import ast_nodes as ast


class TranspileError(Exception):
    """转译错误。"""


# ============================================================
# 符号映射表
# ============================================================

# Matha 内建函数 → TypeScript 等价（含类型注解）
MATHA_TO_TS: dict[str, str] = {
    "sin": "Math.sin", "cos": "Math.cos", "tan": "Math.tan",
    "asin": "Math.asin", "acos": "Math.acos", "atan": "Math.atan",
    "sinh": "Math.sinh", "cosh": "Math.cosh", "tanh": "Math.tanh",
    "sqrt": "Math.sqrt", "ln": "Math.log", "log10": "Math.log10",
    "log2": "Math.log2", "exp": "Math.exp", "abs": "Math.abs",
    "floor": "Math.floor", "ceil": "Math.ceil", "round": "Math.round",
    "max": "Math.max", "min": "Math.min",
    "pi": "Math.PI", "e": "Math.E", "tau": "(2 * Math.PI)",
}

# Matha 类型 → TypeScript 类型
TYPE_MAP: dict[str, str] = {
    "int": "number",
    "float": "number",
    "double": "number",
    "bool": "boolean",
    "string": "string",
    "any": "any",
}


# ============================================================
# TypeScript 转译器
# ============================================================

class TypeScriptTranspiler:
    """把 Matha AST 转译为 TypeScript 源码。"""

    def __init__(self, add_types: bool = True):
        self.indent = 0
        self.lines: list[str] = []
        self.add_types = add_types  # 是否添加类型注解
        self._func_return_types: dict[str, str] = {}

    def transpile(self, source: str) -> str:
        """转译 Matha 源码为 TypeScript 源码。"""
        program = Parser(source).parse()
        self.lines = [
            "// 由 Matha transpiler 自动生成",
            "// Generated by Matha Transpiler",
            f'// Source: {source[:60]}...',
            "",
            '/// <reference types="node" />',
            "",
            "const math = require('math');",
            "",
        ]
        for decl in program.decls:
            self._transpile_decl(decl)
        return "\n".join(self.lines) + "\n"

    def _pad(self) -> str:
        return "  " * self.indent

    def _transpile_decl(self, decl) -> None:
        if isinstance(decl, ast.FuncDef):
            self._transpile_func(decl)
        elif isinstance(decl, ast.Binding):
            target = self._transpile_expr(decl.target)
            value = self._transpile_expr(decl.value) if decl.value else "null"
            ret_type = self._infer_type(decl.value)
            if self.add_types and ret_type:
                self.lines.append(f"const {target}: {ret_type} = {value};")
            else:
                self.lines.append(f"const {target} = {value};")
        elif isinstance(decl, ast.MechUnit):
            if decl.body and isinstance(decl.body, ast.CodeBlock):
                for stmt in decl.body.stmts:
                    self._transpile_stmt(stmt)
        elif isinstance(decl, ast.ModuleDecl):
            for inner in decl.decls:
                self._transpile_decl(inner)

    def _transpile_func(self, fn: ast.FuncDef) -> None:
        name = fn.name
        params = ""
        ret_type = "void"

        if fn.body and isinstance(fn.body, ast.Lambda):
            params_list = fn.body.params if fn.body.params else []
            params = ", ".join(
                f"{p.name}: {self._infer_param_type(p)}" if self.add_types else p.name
                for p in params_list
            )
            body_type = self._infer_type(fn.body.body)
            if body_type:
                ret_type = body_type
                self._func_return_types[name] = body_type

        self.lines.append(f"function {name}({params}): {ret_type} {{")
        self.indent += 1

        if fn.body and isinstance(fn.body, ast.Lambda):
            expr = self._transpile_expr(fn.body.body)
            self.lines.append(f"{self._pad()}return {expr};")
        elif fn.body and isinstance(fn.body, ast.CodeBlock):
            for stmt in fn.body.stmts:
                self._transpile_stmt(stmt)
        else:
            self.lines.append(f"{self._pad()}return null as {ret_type};")

        self.indent -= 1
        self.lines.append("}")
        self.lines.append("")

    def _transpile_stmt(self, stmt) -> None:
        pad = self._pad()
        if isinstance(stmt, ast.Binding):
            target = self._transpile_expr(stmt.target)
            value = self._transpile_expr(stmt.value) if stmt.value else "null"
            ann = f": {self._infer_type(stmt.value)}" if (self.add_types and self._infer_type(stmt.value)) else ""
            self.lines.append(f"{pad}let {target}{ann} = {value};")
        elif isinstance(stmt, ast.GenStmt):
            if hasattr(stmt, 'content') and stmt.content:
                content = stmt.content
                if isinstance(content, ast.OutputTrail):
                    if content.output:
                        expr = self._transpile_expr(content.output.expr)
                        self.lines.append(f"{pad}console.log({expr});")
                elif isinstance(content, ast.FileMarker):
                    pass
        elif isinstance(stmt, ast.Output):
            expr = self._transpile_expr(stmt.expr)
            self.lines.append(f"{pad}console.log({expr});")
        elif isinstance(stmt, ast.IfStmt):
            cond = self._transpile_expr(stmt.cond)
            self.lines.append(f"{pad}if ({cond}) {{")
            self.indent += 1
            if stmt.then_block and isinstance(stmt.then_block, ast.CodeBlock):
                for s in stmt.then_block.stmts:
                    self._transpile_stmt(s)
            self.indent -= 1
            if stmt.else_block:
                self.lines.append(f"{pad}}} else {{")
                self.indent += 1
                if isinstance(stmt.else_block, ast.CodeBlock):
                    for s in stmt.else_block.stmts:
                        self._transpile_stmt(s)
                else:
                    self.lines.append(f"{self._pad()}// else block")
                self.indent -= 1
            self.lines.append(f"{pad}}}")
        elif isinstance(stmt, ast.LoopWhile):
            cond = self._transpile_expr(stmt.cond)
            self.lines.append(f"{pad}while ({cond}) {{")
            self.indent += 1
            if stmt.body and isinstance(stmt.body, ast.CodeBlock):
                for s in stmt.body.stmts:
                    self._transpile_stmt(s)
            self.indent -= 1
            self.lines.append(f"{pad}}}")
        elif isinstance(stmt, ast.CodeBlock):
            for s in stmt.stmts:
                self._transpile_stmt(s)

    def _transpile_expr(self, expr) -> str:
        if expr is None:
            return "null"
        if isinstance(expr, ast.IntegerLit):
            return str(expr.value)
        if isinstance(expr, ast.FloatLit):
            return str(expr.value)
        if isinstance(expr, ast.StringLit):
            import json
            return json.dumps(expr.value, ensure_ascii=False)
        if isinstance(expr, ast.BoolLit):
            return "true" if expr.value else "false"
        if isinstance(expr, ast.Variable):
            name = expr.name
            if name == "真":
                return "true"
            if name == "假":
                return "false"
            if name in MATHA_TO_TS:
                return MATHA_TO_TS[name]
            return name
        if isinstance(expr, ast.BinaryOp):
            left = self._transpile_expr(expr.left)
            right = self._transpile_expr(expr.right)
            op = self._map_op(expr.op)
            return f"({left} {op} {right})"
        if isinstance(expr, ast.UnaryOp):
            operand = self._transpile_expr(expr.operand)
            if expr.op == "-":
                return f"(-{operand})"
            if expr.op == "^":
                return f"Math.sqrt({operand})"
            return f"({expr.op}{operand})"
        if isinstance(expr, ast.Lambda):
            params = ", ".join(p.name for p in expr.params) if expr.params else ""
            body = self._transpile_expr(expr.body)
            return f"(({params}): any => {body})"
        if isinstance(expr, ast.FuncApp):
            arg = self._transpile_expr(expr.arg)
            if isinstance(expr.func, ast.Variable):
                name = expr.func.name
                if name in MATHA_TO_TS:
                    mapped = MATHA_TO_TS[name]
                    if name == "len":
                        return f"({arg}).length"
                    if name == "ord":
                        return f"({arg}).charCodeAt(0)"
                    return f"{mapped}({arg})"
            fn = self._transpile_expr(expr.func)
            return f"{fn}({arg})"
        if isinstance(expr, ast.IfExpr):
            cond = self._transpile_expr(expr.cond)
            then = self._transpile_expr(expr.then)
            els = self._transpile_expr(expr.else_)
            return f"({cond} ? {then} : {els})"
        if isinstance(expr, ast.CodeBlock):
            parts = []
            for s in expr.stmts:
                if isinstance(s, ast.Binding):
                    target = self._transpile_expr(s.target)
                    value = self._transpile_expr(s.value) if s.value else "null"
                    parts.append(f"{target} = {value}")
            return "; ".join(parts) if parts else "null"
        return "null /* 未转译: {} */".format(type(expr).__name__)

    def _infer_type(self, expr) -> str | None:
        """推断表达式的 TypeScript 类型。"""
        if expr is None:
            return None
        if isinstance(expr, ast.IntegerLit):
            return "number"
        if isinstance(expr, ast.FloatLit):
            return "number"
        if isinstance(expr, ast.StringLit):
            return "string"
        if isinstance(expr, ast.BoolLit):
            return "boolean"
        if isinstance(expr, ast.Variable):
            if expr.name in ("真", "假"):
                return "boolean"
            return "any"
        if isinstance(expr, ast.BinaryOp):
            return "number"
        if isinstance(expr, ast.UnaryOp):
            if expr.op in ("+", "-"):
                return "number"
            return "boolean"
        if isinstance(expr, ast.FuncApp):
            if isinstance(expr.func, ast.Variable):
                if expr.func.name in MATHA_TO_TS:
                    return "number"
            return "any"
        if isinstance(expr, ast.IfExpr):
            return "any"
        return "any"

    def _infer_param_type(self, param) -> str:
        """推断参数类型。"""
        if hasattr(param, 'type') and param.type:
            return TYPE_MAP.get(param.type, "any")
        return "any"

    @staticmethod
    def _map_op(op: str) -> str:
        """Matha 运算符 → TypeScript 运算符。"""
        mapping = {
            "+": "+", "-": "-", "*": "*", "/": "/", "%": "%",
            "^": "**", "=": "===", "!=": "!==",
            "<": "<", ">": ">", "<=": "<=", ">=": ">=",
            "&&": "&&", "||": "||", "!": "!",
        }
        return mapping.get(op, op)


# ============================================================
# 统一入口（扩展）
# ============================================================

def transpile(source: str, target: str = "python") -> str:
    """把 Matha 源码转译为目标语言源码。

    Args:
        source: Matha 源码
        target: "python" | "javascript" | "typescript" | "json"

    Returns:
        目标语言源码字符串
    """
    target = target.lower()
    if target in ("python", "py"):
        from src.transpiler import PythonTranspiler
        return PythonTranspiler().transpile(source)
    if target in ("javascript", "js"):
        from src.transpiler import JavaScriptTranspiler
        return JavaScriptTranspiler().transpile(source)
    if target in ("typescript", "ts"):
        return TypeScriptTranspiler().transpile(source)
    if target == "json":
        from src.ast_serializer import program_to_json
        return program_to_json(source)
    raise TranspileError(f"不支持的转译目标: {target}")
